In [1]:
import pandas as pd

### Data DisGeNET

In [2]:
#Loading the CSV file into a DataFrame
gene_associations = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Disgenet\gene_associations.tsv', delimiter='\t')
gene_associations

,geneId,geneSymbol,DSI,DPI,PLI,protein_class_name,protein_class,NofDiseases,NofPmids
0,1,A1BG,0.700,0.538,4.991700e-09,Receptor,DTO_05007575,27,20
1,2,A2M,0.529,0.769,4.522900e-11,Enzyme modulator,DTO_05007584,147,145
2,3,A2MP1,NaN,NaN,NaN,NaN,NaN,1,1
3,9,NAT1,0.536,0.846,1.929400e-14,Enzyme,DTO_05007624,133,184
4,10,NAT2,0.451,0.885,3.274400e-06,Enzyme,DTO_05007624,311,627
...,...,...,...,...,...,...,...,...,...
21666,115482722,H3P33,0.736,0.346,NaN,NaN,NaN,19,15
21667,115482723,H3P40,0.506,0.846,NaN,NaN,NaN,175,202
21668,115561815,LNC-LBCS,0.890,0.077,NaN,NaN,NaN,3,1
21669,115804232,CEROX1,NaN,NaN,NaN,NaN,NaN,1,1
21670,115891964,MIR223HG,0.861,0.077,NaN,NaN,NaN,4,1

In [3]:
#Loading the CSV file into a DataFrame
variant_to_gene_mappings = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Disgenet\variant_to_gene_mappings.tsv', delimiter='\t')
variant_to_gene_mappings

              snpId     geneId       geneSymbol sourceId
0         rs7980288          2              A2M      VEP
1         rs7980288          2              A2M    DBSNP
2         rs3832852          2              A2M    DBSNP
3             rs669          2              A2M      VEP
4             rs669          2              A2M    DBSNP
...             ...        ...              ...      ...
361962  rs556554798  115072896  SLCO1B3-SLCO1B7      VEP
361963   rs11045626  115072896  SLCO1B3-SLCO1B7      VEP
361964    rs4149117  115072896  SLCO1B3-SLCO1B7      VEP
361965     rs629444  115482690            H2BP5      VEP
361966    rs3803700  115804232           CEROX1      VEP

[361967 rows x 4 columns]

In [4]:
#Loading the CSV file into a DataFrame
variant_associations = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Disgenet\variant_associations.tsv', delimiter='\t')
variant_associations

,snpId,class,chromosome,position,most_severe_consequence,DSI,DPI,NofDiseases,NofPmids
0,rs1000005,snv,21,33060745,intron variant,NaN,NaN,1,1
1,rs10000770,snv,4,142693109,intron variant,1.000,0.04,1,1
2,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1
3,rs1000096,snv,4,38691214,intron variant,NaN,NaN,1,1
4,rs10001106,snv,4,10125817,intergenic variant,0.925,0.12,3,4
...,...,...,...,...,...,...,...,...,...
194510,rs999943,snv,6,33656956,intron variant,1.000,0.08,1,1
194511,rs999944,snv,2,64822719,intergenic variant,1.000,0.08,1,1
194512,rs999947969,snv,7,80671145,synonymous variant,0.827,0.08,7,7
194513,rs9999653,snv,4,55632082,intron variant,1.000,0.08,1,1
194514,rs9999820,snv,4,155197173,intron variant,0.925,0.08,2,1

In [5]:
#Merging 'variant_associations' and 'variant_to_gene_mappings'
Disgenet_merged = pd.merge(variant_associations, variant_to_gene_mappings, how='inner', on='snpId')
Disgenet_merged

,snpId,class,chromosome,position,most_severe_consequence,DSI,DPI,NofDiseases,NofPmids,geneId,geneSymbol,sourceId
0,rs1000005,snv,21,33060745,intron variant,NaN,NaN,1,1,101930746,LINC00945,DBSNP
1,rs10000770,snv,4,142693109,intron variant,1.000,0.04,1,1,8821,INPP4B,DBSNP
2,rs10000770,snv,4,142693109,intron variant,1.000,0.04,1,1,8821,INPP4B,VEP
3,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,IGHMBP2,VEP
4,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,IGHMBP2,DBSNP
...,...,...,...,...,...,...,...,...,...,...,...,...
361962,rs999947969,snv,7,80671145,synonymous variant,0.827,0.08,7,7,948,CD36,DBSNP
361963,rs999947969,snv,7,80671145,synonymous variant,0.827,0.08,7,7,948,CD36,VEP
361964,rs9999653,snv,4,55632082,intron variant,1.000,0.08,1,1,10874,NMU,VEP
361965,rs9999653,snv,4,55632082,intron variant,1.000,0.08,1,1,10874,NMU,DBSNP
361966,rs9999820,snv,4,155197173,intron variant,0.925,0.08,2,1,4887,NPY2R,DBSNP

In [6]:
#Merging 'variant_associations+variant_to_gene_mappings' and 'gene_associations'
Disgenet_all_merged = pd.merge(Disgenet_merged, gene_associations, how='inner', on='geneId')
Disgenet_all_merged

,snpId,class,chromosome,position,most_severe_consequence,DSI_x,DPI_x,NofDiseases_x,NofPmids_x,geneId,geneSymbol_x,sourceId,geneSymbol_y,DSI_y,DPI_y,PLI,protein_class_name,protein_class,NofDiseases_y,NofPmids_y
0,rs10000770,snv,4,142693109,intron variant,1.0,0.04,1,1,8821,INPP4B,DBSNP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
1,rs10000770,snv,4,142693109,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
2,rs10006418,snv,4,142691588,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
3,rs10006418,snv,4,142691588,intron variant,1.0,0.04,1,1,8821,INPP4B,DBSNP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
4,rs10012488,snv,4,142671933,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346532,rs998297769,snv,X,151962587,stop gained,NaN,NaN,1,0,2564,GABRE,DBSNP,GABRE,0.839,0.231,0.000184,Ion channel,DTO_01300327,8,4
346533,rs999036825,snv,19,16228789,missense variant,1.0,0.08,1,0,8907,AP1M1,VEP,AP1M1,0.839,0.154,0.712510,Extracellular structure,DTO_05007621,5,1
346534,rs999036825,snv,19,16228789,missense variant,1.0,0.08,1,0,8907,AP1M1,DBSNP,AP1M1,0.839,0.154,0.712510,Extracellular structure,DTO_05007621,5,1
346535,rs9992013,snv,4,2257736,intron variant,NaN,NaN,1,1,10608,MXD4,VEP,MXD4,0.722,0.115,0.776350,Transcription factor,DTO_05007542,19,9
346536,rs9992013,snv,4,2257736,intron variant,NaN,NaN,1,1,10608,MXD4,DBSNP,MXD4,0.722,0.115,0.776350,Transcription factor,DTO_05007542,19,9

### Data Harmonizome

In [7]:
#Loading the CSV file into a DataFrame
gene_list_terms = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\gene_list_terms.txt', delimiter='\t')
gene_list_terms

         GeneSym  NA  GeneID
0        PITPNM2  na   57605
1           VRK1  na    7443
2         OGFOD2  na   79676
3      KIDINS220  na   57498
4         IGSF10  na  285313
...          ...  ..     ...
10700      EBAG9  na    9166
10701   IGHV1-69  na   28461
10702      ERAL1  na   26284
10703    SLC27A5  na   10998
10704      CD177  na   57126

[10705 rows x 3 columns]

In [8]:
#Loading the CSV file into a DataFrame
# gene_set_library_crisp = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\gene_set_library_crisp.txt', delimiter='\t')
# gene_set_library_crisp

In [9]:
# Empty list to store the data
data = []

# Open the file and read all the lines
with open(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\gene_set_library_crisp.txt') as file:
    for line in file:
        # Split the line values and add to the data list
        split_line = line.strip().split('\t')
        data.append([split_line[0], split_line[1], split_line[2]])

# Create DataFrame
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Display DataFrame
print(df)

                                                 Column1          Column2  \
0                          eating behavior disinhibition        metabolic
1                        phenylthiocarbamide sensitivity  normalvariation
2                    bitter perception; sweet preference  normalvariation
3                   ability to taste phenylthiocarbamide            other
4                                          dental caries        infection
...                                                  ...              ...
12770                            mucopolysaccharidosis i            other
12771                          hypertension;  benazepril          unknown
12772     congenital fibrosis of the extraocular muscles    developmental
12773  meckel-gruber syndrome; abnormalities, multipl...          unknown
12774  lung diseases, interstitial; scleroderma, diff...          unknown

        Column3
0       TAS2R38
1       TAS2R38
2       TAS2R38
3       TAS2R38
4       TAS2R38
...         ...
12770      IDUA
12771      PRCP
12772    KIF21A
12773      MKS1
12774  TRBV20-1

[12775 rows x 3 columns]

In [10]:
#saving the DataFrame to a CSV file 
df.to_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\df.csv', index=False)

In [11]:
#Loading the CSV file into a DataFrame
gene_set_library_crisp = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\df.csv')
gene_set_library_crisp

,Column1,Column2,Column3
0,eating behavior disinhibition,metabolic,TAS2R38
1,phenylthiocarbamide sensitivity,normalvariation,TAS2R38
2,bitter perception; sweet preference,normalvariation,TAS2R38
3,ability to taste phenylthiocarbamide,other,TAS2R38
4,dental caries,infection,TAS2R38
...,...,...,...
12770,mucopolysaccharidosis i,other,IDUA
12771,hypertension; benazepril,unknown,PRCP
12772,congenital fibrosis of the extraocular muscles,developmental,KIF21A
12773,"meckel-gruber syndrome; abnormalities, multipl...",unknown,MKS1
12774,"lung diseases, interstitial; scleroderma, diff...",unknown,TRBV20-1

In [12]:
#Merging 'gene_list_terms' and 'gene_set_library_crisp'
merged_df = pd.merge(gene_list_terms, gene_set_library_crisp, how='inner', left_on='GeneSym', right_on='Column3')
print(merged_df)

        GeneSym  NA  GeneID  \
0       PITPNM2  na   57605
1         ABCB9  na   23457
2          CROT  na   54677
3        FBXO11  na   80204
4        FBXO11  na   80204
...         ...  ..     ...
12770     EBAG9  na    9166
12771  IGHV1-69  na   28461
12772     ERAL1  na   26284
12773   SLC27A5  na   10998
12774     CD177  na   57126

                                                 Column1          Column2  \
0                                            neutrophils           immune
1                                     drug-related genes  pharmacogenomic
2                                   tobacco use disorder          unknown
3                                               vitiligo            other
4                                            lymphocytes           immune
...                                                  ...              ...
12770                         early-stage breast cancers           cancer
12771  leukemia, lymphocytic, chronic, b-cell; lympho...           cancer
12772                skeletal responsiveness to estrogen        metabolic
12773  fatty liver; insulin resistance; metabolic syn...        metabolic
12774                              low expression of nb1            other

        Column3
0       PITPNM2
1         ABCB9
2          CROT
3        FBXO11
4        FBXO11
...         ...
12770     EBAG9
12771  IGHV1-69
12772     ERAL1
12773   SLC27A5
12774     CD177

[12775 rows x 6 columns]

In [13]:
#saving the DataFrame to a CSV file 
merged_df.to_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\merged.csv', index=False)

In [14]:
Harmonizome = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\merged.csv')
Harmonizome

,GeneSym,NA,GeneID,Column1,Column2,Column3
0,PITPNM2,na,57605,neutrophils,immune,PITPNM2
1,ABCB9,na,23457,drug-related genes,pharmacogenomic,ABCB9
2,CROT,na,54677,tobacco use disorder,unknown,CROT
3,FBXO11,na,80204,vitiligo,other,FBXO11
4,FBXO11,na,80204,lymphocytes,immune,FBXO11
...,...,...,...,...,...,...
12770,EBAG9,na,9166,early-stage breast cancers,cancer,EBAG9
12771,IGHV1-69,na,28461,"leukemia, lymphocytic, chronic, b-cell; lympho...",cancer,IGHV1-69
12772,ERAL1,na,26284,skeletal responsiveness to estrogen,metabolic,ERAL1
12773,SLC27A5,na,10998,fatty liver; insulin resistance; metabolic syn...,metabolic,SLC27A5
12774,CD177,na,57126,low expression of nb1,other,CD177

In [15]:
#Dropping columns  
Harmonizome = Harmonizome.drop(columns=['NA','GeneSym'])
Harmonizome

,GeneID,Column1,Column2,Column3
0,57605,neutrophils,immune,PITPNM2
1,23457,drug-related genes,pharmacogenomic,ABCB9
2,54677,tobacco use disorder,unknown,CROT
3,80204,vitiligo,other,FBXO11
4,80204,lymphocytes,immune,FBXO11
...,...,...,...,...
12770,9166,early-stage breast cancers,cancer,EBAG9
12771,28461,"leukemia, lymphocytic, chronic, b-cell; lympho...",cancer,IGHV1-69
12772,26284,skeletal responsiveness to estrogen,metabolic,ERAL1
12773,10998,fatty liver; insulin resistance; metabolic syn...,metabolic,SLC27A5
12774,57126,low expression of nb1,other,CD177

In [16]:
#Renaming columns
df = Harmonizome.rename(columns={'Column1': 'Disease Class', 'Column2': 'Category', 'Column3': 'Gene/Protein Symbol'})
df

,GeneID,Disease Class,Category,Gene/Protein Symbol
0,57605,neutrophils,immune,PITPNM2
1,23457,drug-related genes,pharmacogenomic,ABCB9
2,54677,tobacco use disorder,unknown,CROT
3,80204,vitiligo,other,FBXO11
4,80204,lymphocytes,immune,FBXO11
...,...,...,...,...
12770,9166,early-stage breast cancers,cancer,EBAG9
12771,28461,"leukemia, lymphocytic, chronic, b-cell; lympho...",cancer,IGHV1-69
12772,26284,skeletal responsiveness to estrogen,metabolic,ERAL1
12773,10998,fatty liver; insulin resistance; metabolic syn...,metabolic,SLC27A5
12774,57126,low expression of nb1,other,CD177

In [17]:
#creating a .csv file
df.to_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\Harmonizome.csv', index=False)

In [18]:
#Loading the CSV file into a DataFrame
df_Harmonizome = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Data\Protein\Harmonizome 3.0\Harmonizome.csv')
df_Harmonizome

,GeneID,Disease Class,Category,Gene/Protein Symbol
0,57605,neutrophils,immune,PITPNM2
1,23457,drug-related genes,pharmacogenomic,ABCB9
2,54677,tobacco use disorder,unknown,CROT
3,80204,vitiligo,other,FBXO11
4,80204,lymphocytes,immune,FBXO11
...,...,...,...,...
12770,9166,early-stage breast cancers,cancer,EBAG9
12771,28461,"leukemia, lymphocytic, chronic, b-cell; lympho...",cancer,IGHV1-69
12772,26284,skeletal responsiveness to estrogen,metabolic,ERAL1
12773,10998,fatty liver; insulin resistance; metabolic syn...,metabolic,SLC27A5
12774,57126,low expression of nb1,other,CD177

### Merge the df's - DisGeNET + Harmonizome

In [19]:
#rename the columns for merging

Disgenet_all_merged.rename(columns={'geneId': 'GeneID','geneSymbol':'Gene/Protein Symbol'}, inplace=True)
Disgenet_all_merged

,snpId,class,chromosome,position,most_severe_consequence,DSI_x,DPI_x,NofDiseases_x,NofPmids_x,GeneID,geneSymbol_x,sourceId,geneSymbol_y,DSI_y,DPI_y,PLI,protein_class_name,protein_class,NofDiseases_y,NofPmids_y
0,rs10000770,snv,4,142693109,intron variant,1.0,0.04,1,1,8821,INPP4B,DBSNP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
1,rs10000770,snv,4,142693109,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
2,rs10006418,snv,4,142691588,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
3,rs10006418,snv,4,142691588,intron variant,1.0,0.04,1,1,8821,INPP4B,DBSNP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
4,rs10012488,snv,4,142671933,intron variant,1.0,0.04,1,1,8821,INPP4B,VEP,INPP4B,0.573,0.577,0.552180,NaN,NaN,90,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346532,rs998297769,snv,X,151962587,stop gained,NaN,NaN,1,0,2564,GABRE,DBSNP,GABRE,0.839,0.231,0.000184,Ion channel,DTO_01300327,8,4
346533,rs999036825,snv,19,16228789,missense variant,1.0,0.08,1,0,8907,AP1M1,VEP,AP1M1,0.839,0.154,0.712510,Extracellular structure,DTO_05007621,5,1
346534,rs999036825,snv,19,16228789,missense variant,1.0,0.08,1,0,8907,AP1M1,DBSNP,AP1M1,0.839,0.154,0.712510,Extracellular structure,DTO_05007621,5,1
346535,rs9992013,snv,4,2257736,intron variant,NaN,NaN,1,1,10608,MXD4,VEP,MXD4,0.722,0.115,0.776350,Transcription factor,DTO_05007542,19,9
346536,rs9992013,snv,4,2257736,intron variant,NaN,NaN,1,1,10608,MXD4,DBSNP,MXD4,0.722,0.115,0.776350,Transcription factor,DTO_05007542,19,9

In [20]:
#merging Disgenet + Harmonizome

Disgenet_Harmonizome = pd.merge(Disgenet_all_merged, df_Harmonizome, how='inner', on='GeneID')

Disgenet_Harmonizome

,snpId,class,chromosome,position,most_severe_consequence,DSI_x,DPI_x,NofDiseases_x,NofPmids_x,GeneID,...,DSI_y,DPI_y,PLI,protein_class_name,protein_class,NofDiseases_y,NofPmids_y,Disease Class,Category,Gene/Protein Symbol
0,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
1,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
2,rs1057518588,snv,11,68908632,splice donor variant,0.851,0.16,6,3,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
3,rs1057518588,snv,11,68908632,splice donor variant,0.851,0.16,6,3,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
4,rs1057518943,snv,11,68906163,missense variant,1.000,0.12,5,0,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087375,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,socioeconomic factors,other,ITGBL1
2087376,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,"natriuretic peptide, brain",neurological,ITGBL1
2087377,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,waist-hip ratio,metabolic,ITGBL1
2087378,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,erythrocyte indices,hematological,ITGBL1
2087379,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,socioeconomic factors,other,ITGBL1

In [21]:
#creating a .csv file
Disgenet_Harmonizome.to_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Final\Harmonizome+Disgenet.csv', index=False)

# DisGeNET+Harmonizome

In [22]:
#Loading the CSV file into a DataFrame
df = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Final\Harmonizome+Disgenet.csv')
df

C:\Users\teka_\AppData\Local\Temp\ipykernel_20056\2091845720.py:1: DtypeWarning: Columns (2,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Final\Harmonizome+Disgenet.csv')

,snpId,class,chromosome,position,most_severe_consequence,DSI_x,DPI_x,NofDiseases_x,NofPmids_x,GeneID,...,DSI_y,DPI_y,PLI,protein_class_name,protein_class,NofDiseases_y,NofPmids_y,Disease Class,Category,Gene/Protein Symbol
0,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
1,rs1000091588,snv,11,68935374,stop gained,1.000,0.12,1,1,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
2,rs1057518588,snv,11,68908632,splice donor variant,0.851,0.16,6,3,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
3,rs1057518588,snv,11,68908632,splice donor variant,0.851,0.16,6,3,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
4,rs1057518943,snv,11,68906163,missense variant,1.000,0.12,5,0,3508,...,0.636,0.615,3.021200e-16,NaN,NaN,102,60,iga nephropathy,immune,IGHMBP2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087375,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,socioeconomic factors,other,ITGBL1
2087376,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,"natriuretic peptide, brain",neurological,ITGBL1
2087377,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,waist-hip ratio,metabolic,ITGBL1
2087378,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,erythrocyte indices,hematological,ITGBL1
2087379,rs9557704,snv,13,101575144,intron variant,NaN,NaN,1,1,9358,...,0.705,0.423,1.767100e-09,Receptor,DTO_05007575,27,13,socioeconomic factors,other,ITGBL1

The genes most commonly associated with breast cancer include:

BRCA1 (Breast Cancer 1) Function: Tumor suppressor gene that helps repair damaged DNA. Association: Mutations in BRCA1 significantly increase the risk of developing breast cancer and ovarian cancer.

BRCA2 (Breast Cancer 2) Function: Similar to BRCA1, BRCA2 is also a tumor suppressor gene involved in DNA repair. Association: Mutations in BRCA2 increase the risk of breast cancer, ovarian cancer, and other types of cancer.

TP53 (Tumor Protein p53) Function: Tumor suppressor gene that regulates the cell cycle and prevents the proliferation of cells with damaged DNA. Association: Mutations in TP53 are found in several types of cancer, including breast cancer.

HER2 (Human Epidermal Growth Factor Receptor 2) Function: Gene that encodes a growth factor receptor protein, involved in cell growth. Association: HER2 overexpression is associated with a more aggressive type of breast cancer.

PIK3CA (Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha) Function: Involved in cell growth and survival signals. Association: Mutations in PIK3CA are common in breast cancer and may influence response to treatment.

PTEN (Phosphatase and Tensin Homolog) Function: Tumor suppressor gene that regulates cell growth. Association: Mutations in PTEN can lead to uncontrolled cell growth and are associated with several types of cancer, including breast cancer.

CDH1 (Cadherin 1) Function: Involved in cell adhesion and maintenance of tissue structure. Association: Mutations in CDH1 are associated with lobular breast cancer.

PALB2 (Partner and Localizer of BRCA2) Function: Works together with BRCA2 in DNA repair. Association: Mutations in PALB2 increase the risk of breast cancer.

ATM (Ataxia-Telangiectasia Mutated) Function: Involved in the response to DNA damage. Association: Mutations in ATM are associated with an increased risk of breast cancer.

CHEK2 (Checkpoint Kinase 2) Function: Acts in the response to DNA damage. Association: Mutations in CHEK2 are associated with a moderate increase in the risk of breast cancer.

In [23]:
# List of genes to search for
genes_to_find = ['BRCA1', 'BRCA2', 'TP53', 'HER2', 'PIK3CA', 'PTEN', 'CDH1', 'PALB2', 'ATM', 'CHEK2']

# Filter the DataFrame to include only rows with the specific genes
df_genes_filtered = df[df['Gene/Protein Symbol'].isin(genes_to_find)]

# Use value_counts to count occurrences of each gene
gene_counts = df_genes_filtered['Gene/Protein Symbol'].value_counts()

# Display the counts
print(gene_counts)

Gene/Protein Symbol
BRCA1     280800
TP53      176943
BRCA2      42924
ATM        25298
PTEN        3840
CHEK2       3132
CDH1        2597
PALB2       2460
PIK3CA      2158
Name: count, dtype: int64

In [24]:
#dropping duplicated columns

df = df.drop(columns=['DSI_y', 'DPI_y','NofDiseases_y', 'NofPmids_y', 'geneSymbol_y', 'geneSymbol_x', 'DSI_x', 'DPI_x', 'NofDiseases_x', 'NofPmids_x', 'PLI']).reset_index(drop=True)
df

,snpId,class,chromosome,position,most_severe_consequence,GeneID,sourceId,protein_class_name,protein_class,Disease Class,Category,Gene/Protein Symbol
0,rs1000091588,snv,11,68935374,stop gained,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
1,rs1000091588,snv,11,68935374,stop gained,3508,DBSNP,NaN,NaN,iga nephropathy,immune,IGHMBP2
2,rs1057518588,snv,11,68908632,splice donor variant,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
3,rs1057518588,snv,11,68908632,splice donor variant,3508,DBSNP,NaN,NaN,iga nephropathy,immune,IGHMBP2
4,rs1057518943,snv,11,68906163,missense variant,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
...,...,...,...,...,...,...,...,...,...,...,...,...
2087375,rs9557704,snv,13,101575144,intron variant,9358,VEP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1
2087376,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,"natriuretic peptide, brain",neurological,ITGBL1
2087377,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,waist-hip ratio,metabolic,ITGBL1
2087378,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,erythrocyte indices,hematological,ITGBL1
2087379,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1

In [25]:
##rename the columns post-merging

df.rename(columns={'snpId': 'snpID'}, inplace=True)
df

,snpID,class,chromosome,position,most_severe_consequence,GeneID,sourceId,protein_class_name,protein_class,Disease Class,Category,Gene/Protein Symbol
0,rs1000091588,snv,11,68935374,stop gained,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
1,rs1000091588,snv,11,68935374,stop gained,3508,DBSNP,NaN,NaN,iga nephropathy,immune,IGHMBP2
2,rs1057518588,snv,11,68908632,splice donor variant,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
3,rs1057518588,snv,11,68908632,splice donor variant,3508,DBSNP,NaN,NaN,iga nephropathy,immune,IGHMBP2
4,rs1057518943,snv,11,68906163,missense variant,3508,VEP,NaN,NaN,iga nephropathy,immune,IGHMBP2
...,...,...,...,...,...,...,...,...,...,...,...,...
2087375,rs9557704,snv,13,101575144,intron variant,9358,VEP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1
2087376,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,"natriuretic peptide, brain",neurological,ITGBL1
2087377,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,waist-hip ratio,metabolic,ITGBL1
2087378,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,erythrocyte indices,hematological,ITGBL1
2087379,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1

In [26]:
df.shape

(2087380, 12)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2087380 entries, 0 to 2087379
Data columns (total 12 columns):
 #   Column                   Dtype
---  ------                   -----
 0   snpID                    object
 1   class                    object
 2   chromosome               object
 3   position                 int64
 4   most_severe_consequence  object
 5   GeneID                   int64
 6   sourceId                 object
 7   protein_class_name       object
 8   protein_class            object
 9   Disease Class            object
 10  Category                 object
 11  Gene/Protein Symbol      object
dtypes: int64(2), object(10)
memory usage: 191.1+ MB

In [28]:
df.dtypes

snpID                      object
class                      object
chromosome                 object
position                    int64
most_severe_consequence    object
GeneID                      int64
sourceId                   object
protein_class_name         object
protein_class              object
Disease Class              object
Category                   object
Gene/Protein Symbol        object
dtype: object

In [29]:
df.describe()

           position        GeneID
count  2.087380e+06  2.087380e+06
mean   5.912527e+07  8.002058e+04
std    5.045177e+07  2.722170e+06
min    9.610000e+02  2.000000e+00
25%    2.272703e+07  6.750000e+02
50%    4.309372e+07  3.043000e+03
75%    8.893295e+07  5.053000e+03
max    2.474493e+08  1.005074e+08

In [30]:
nan_per_column = df.isna().sum()
nan_per_column

snpID                           0
class                           0
chromosome                      0
position                        0
most_severe_consequence         0
GeneID                          0
sourceId                        0
protein_class_name         596419
protein_class              596419
Disease Class                   0
Category                        0
Gene/Protein Symbol             0
dtype: int64

In [31]:
df.dropna(inplace=True)
df

,snpID,class,chromosome,position,most_severe_consequence,GeneID,sourceId,protein_class_name,protein_class,Disease Class,Category,Gene/Protein Symbol
174,rs10001410,snv,4,61608511,intron variant,23284,VEP,G-protein coupled receptor,DTO_02300001,biochemical measures,other,LPHN3
175,rs10001410,snv,4,61608511,intron variant,23284,VEP,G-protein coupled receptor,DTO_02300001,"memory, short-term",aging,LPHN3
176,rs10001410,snv,4,61608511,intron variant,23284,DBSNP,G-protein coupled receptor,DTO_02300001,biochemical measures,other,LPHN3
177,rs10001410,snv,4,61608511,intron variant,23284,DBSNP,G-protein coupled receptor,DTO_02300001,"memory, short-term",aging,LPHN3
178,rs1355368,snv,4,61914104,intron variant,23284,VEP,G-protein coupled receptor,DTO_02300001,biochemical measures,other,LPHN3
...,...,...,...,...,...,...,...,...,...,...,...,...
2087375,rs9557704,snv,13,101575144,intron variant,9358,VEP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1
2087376,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,"natriuretic peptide, brain",neurological,ITGBL1
2087377,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,waist-hip ratio,metabolic,ITGBL1
2087378,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,erythrocyte indices,hematological,ITGBL1
2087379,rs9557704,snv,13,101575144,intron variant,9358,DBSNP,Receptor,DTO_05007575,socioeconomic factors,other,ITGBL1

In [32]:
nan_per_column = df.isna().sum()
nan_per_column

snpID                      0
class                      0
chromosome                 0
position                   0
most_severe_consequence    0
GeneID                     0
sourceId                   0
protein_class_name         0
protein_class              0
Disease Class              0
Category                   0
Gene/Protein Symbol        0
dtype: int64

In [33]:
df.columns

Index(['snpID', 'class', 'chromosome', 'position', 'most_severe_consequence',
       'GeneID', 'sourceId', 'protein_class_name', 'protein_class',
       'Disease Class', 'Category', 'Gene/Protein Symbol'],
      dtype='object')

In [34]:
df['Gene/Protein Symbol'].value_counts()

Gene/Protein Symbol
BRCA1      280800
TP53       176943
CFTR       100125
ACE         64480
MLH1        48448
            ...
CYP26A1         1
TIMP4           1
TAS1R3          1
SLC22A6         1
TFF2            1
Name: count, Length: 1333, dtype: int64

The genes most commonly associated with breast cancer include:

BRCA1 (Breast Cancer 1)
Function: Tumor suppressor gene that helps repair damaged DNA.
Association: Mutations in BRCA1 significantly increase the risk of developing breast cancer and ovarian cancer.

BRCA2 (Breast Cancer 2)
Function: Similar to BRCA1, BRCA2 is also a tumor suppressor gene involved in DNA repair.
Association: Mutations in BRCA2 increase the risk of breast cancer, ovarian cancer, and other types of cancer.

TP53 (Tumor Protein p53)
Function: Tumor suppressor gene that regulates the cell cycle and prevents the proliferation of cells with damaged DNA.
Association: Mutations in TP53 are found in several types of cancer, including breast cancer.

HER2 (Human Epidermal Growth Factor Receptor 2)
Function: Gene that encodes a growth factor receptor protein, involved in cell growth.
Association: HER2 overexpression is associated with a more aggressive type of breast cancer.

PIK3CA (Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha)
Function: Involved in cell growth and survival signals.
Association: Mutations in PIK3CA are common in breast cancer and may influence response to treatment.

PTEN (Phosphatase and Tensin Homolog)
Function: Tumor suppressor gene that regulates cell growth.
Association: Mutations in PTEN can lead to uncontrolled cell growth and are associated with several types of cancer, including breast cancer.

CDH1 (Cadherin 1)
Function: Involved in cell adhesion and maintenance of tissue structure.
Association: Mutations in CDH1 are associated with lobular breast cancer.

PALB2 (Partner and Localizer of BRCA2)
Function: Works together with BRCA2 in DNA repair.
Association: Mutations in PALB2 increase the risk of breast cancer.

ATM (Ataxia-Telangiectasia Mutated)
Function: Involved in the response to DNA damage.
Association: Mutations in ATM are associated with an increased risk of breast cancer.

CHEK2 (Checkpoint Kinase 2)
Function: Acts in the response to DNA damage.
Association: Mutations in CHEK2 are associated with a moderate increase in the risk of breast cancer.

In [35]:
# List of genes to search for
genes_to_find = ['BRCA1', 'BRCA2', 'TP53', 'HER2', 'PIK3CA', 'PTEN', 'CDH1', 'PALB2', 'ATM', 'CHEK2']

# Filtering the DataFrame to contain only the rows with the specific genes
df_genes_filtered = df[df['Gene/Protein Symbol'].isin(genes_to_find)]

# Using value_counts to count the occurrences of each gene
gene_counts = df_genes_filtered['Gene/Protein Symbol'].value_counts()

# Displaying the counts
print(gene_counts)

Gene/Protein Symbol
BRCA1     280800
TP53      176943
BRCA2      42924
ATM        25298
PTEN        3840
CHEK2       3132
PIK3CA      2158
Name: count, dtype: int64

#renaming the synomym GeneIDs as per official names
#both Harmozinome and DisGENet utilize the "NCBI Entrez" for gene identification.

In [36]:
def rename_genes_in_dataframe(df, gene_input):
    """
    Function to rename gene synonyms in a DataFrame.

    Parameters:
    df (DataFrame): The DataFrame where the genes will be renamed.
    gene_input (str): String with gene synonyms and common name in the format 'synonyms; common_name'.

    Returns:
    DataFrame: The updated DataFrame with genes renamed.
    """
    # Separate the synonyms from the common name
    gene_synonyms, common_name = gene_input.split(';')
    
    # Convert the synonym string into a list
    synonym_list = [gene.strip() for gene in gene_synonyms.split(',')]
    
    # Replace the synonyms with the common name in the DataFrame
    df.replace(synonym_list, common_name.strip(), inplace=True)
    
    return df

In [37]:
# List of gene inputs to be renamed
gene_inputs = [
    "BCC7, LFS1, P53, TRP53; TP53",
    "BRCAI, BRCC1, BROVCA1, FANCS, IRIS, PNCA4, PPP1R53, PSCP, RNF53; BRCA1",
    "AT1, ATA, ATC, ATD, ATDC, ATE, TEL1, TELO1; ATM",
    "BRCC2, BROVCA2, FACD, FAD, FAD1, FANCD, FANCD1, GLM3, PNCA2, XRCC11, RP11-298P3.4; BRCA2",
    "10q23del, BZS, CWS1, DEC, GLM2, MHAM, MMAC1, PTEN1, TEP1; PTEN",
    "CDS1, CHK2, HuCds1, LFS2, PP1425, RAD53, hCds1, RP11-436C9.1; CHEK2",
    "CLOVE, CWS5, MCAP, MCM, MCMTC, PI3K, p110-alpha; PIK3CA"]

# Loop to apply the function to each entry
for gene_input in gene_inputs:
    df = rename_genes_in_dataframe(df, gene_input)

In [38]:
# List of genes to keep
genes_to_keep = ['TP53', 'BRCA1','ATM', 'BRCA2', 'PTEN', 'CHEK2', 'PIK3CA']

# Filtering the DataFrame to keep only the specific genes
df = df[df['Gene/Protein Symbol'].isin(genes_to_keep)].reset_index(drop=True)

# Displaying the updated DataFrame
df

,snpID,class,chromosome,position,most_severe_consequence,GeneID,sourceId,protein_class_name,protein_class,Disease Class,Category,Gene/Protein Symbol
0,rs1000256867,snv,17,7673550,missense variant,7157,VEP,Transcription factor,DTO_05007542,cervical intraepithelial neoplasia; papillomav...,cancer,TP53
1,rs1000256867,snv,17,7673550,missense variant,7157,VEP,Transcription factor,DTO_05007542,"carcinoma, squamous cell; esophageal neoplasms...",cancer,TP53
2,rs1000256867,snv,17,7673550,missense variant,7157,VEP,Transcription factor,DTO_05007542,duodenal ulcer; helicobacter infections; stoma...,cancer,TP53
3,rs1000256867,snv,17,7673550,missense variant,7157,VEP,Transcription factor,DTO_05007542,oral lichen planus,infection,TP53
4,rs1000256867,snv,17,7673550,missense variant,7157,VEP,Transcription factor,DTO_05007542,kaposi's sarcoma,cancer,TP53
...,...,...,...,...,...,...,...,...,...,...,...,...
535090,rs967624732,snv,17,43097269,missense variant,672,VEP,Enzyme,DTO_05007624,"breast neoplasms; cell transformation, neoplas...",cancer,BRCA1
535091,rs967624732,snv,17,43097269,missense variant,672,VEP,Enzyme,DTO_05007624,"breast cancer, male",cancer,BRCA1
535092,rs967624732,snv,17,43097269,missense variant,672,VEP,Enzyme,DTO_05007624,breast neoplasms; mammary neoplasms; neoplasms...,cancer,BRCA1
535093,rs967624732,snv,17,43097269,missense variant,672,VEP,Enzyme,DTO_05007624,ovarian diseases,reproduction,BRCA1
535094,rs967624732,snv,17,43097269,missense variant,672,VEP,Enzyme,DTO_05007624,endometrial carcinoma,cancer,BRCA1

In [39]:
#CREATING A CLEAN DATA 
df.to_csv(r'C:\Users\teka_\DATA SCIENCE\Concordia-Bootcamps\FINAL PROJECT\Jupyter Notebook\1-used\df_wo_othersGens.csv', index=False)